[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
expense_tracker = "B8B2VeAcjRdVtt1HTwkSTUefn7WrfXfsp6VBmsod9uws"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ibrahimarshad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
